version: "3"
services:
  redis:
    image: redislabs/redisearch:2.4.8
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - "./docker/redis-data:/data"

  mysql:
    image: mysql:5.7.38
    container_name: mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - "./docker/mysql-data:/var/lib/mysql"
      - "./sql/ddl.sql:/docker-entrypoint-initdb.d/1.sql:ro"
      - "./sql/init.sql:/docker-entrypoint-initdb.d/2.sql:ro"
